name = input("enter your name:")
age = int(input("enter your age:"))
college = input("enter your college name:")
branch = input("enter your branch:")
print("        ")
print("student details")
print("         ")
print("name   :",name)
print("age    :",age)
print("college:",college)
print("branch :",branch)